import { getCollection } from 'astro:content';

// Number of update cards per page. Page 1 is the docs index page
// (src/content-src/docs/index.mdx); pages 2+ are standalone routes
// generated by src/pages/[page]/index.astro and src/pages/fr/[page]/.
export const UPDATES_PER_PAGE = 20;

export async function getSortedUpdates() {
  const entries = await getCollection('updates');
  return entries.sort((a, b) => b.data.date.valueOf() - a.data.date.valueOf());
}

export async function getUpdatesPageCount() {
  const entries = await getCollection('updates');
  return Math.max(1, Math.ceil(entries.length / UPDATES_PER_PAGE));
}

// Page chrome for the standalone paginated routes. Page 1 carries the same
// wording in src/content-src/docs/index.mdx — keep the two in sync.
export const updatesPageStrings = {
  en: {
    title: 'Updates',
    description: 'Latest updates and announcements for Argonaut.',
    lead: 'The latest features, fixes, and announcements for Argonaut.',
  },
  fr: {
    title: 'Nouveautés',
    description: 'Dernières nouveautés et annonces pour Argonaut.',
    lead: 'Les dernières fonctionnalités, corrections et annonces pour Argonaut.',
  },
} as const;
