import { getCollection } from 'astro:content';

// Number of update cards per page. Page 1 is the docs index page
// (src/content-src/docs/index.mdx); pages 2+ are standalone routes
// generated by src/pages/[page]/index.astro and src/pages/fr/[page]/.
export const UPDATES_PER_PAGE = 20;

export type Locale = 'en' | 'fr';

export async function getSortedUpdates() {
  const entries = await getCollection('updates');
  return entries.sort((a, b) => b.data.date.valueOf() - a.data.date.valueOf());
}

export async function getUpdatesPageCount() {
  const entries = await getCollection('updates');
  return Math.max(1, Math.ceil(entries.length / UPDATES_PER_PAGE));
}

// Slugify a tag's English label into a stable key. Tags are free-form and
// localized, so the English label is the canonical identity: it keeps a tag
// as one filter route (/tags/<slug>/) and one colour even when the label
// differs by locale. e.g. "Security fix" -> "security-fix".
export function tagSlug(en: string): string {
  return en
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Deterministic pill variant per tag so a given tag always renders the same
// colour across cards and pages. Hashes the slug across the theme's pill set.
const TAG_VARIANTS = ['pill-green', 'pill-info', 'pill-warn'] as const;
export function tagVariant(slug: string): (typeof TAG_VARIANTS)[number] {
  let hash = 0;
  for (let i = 0; i < slug.length; i++) hash = (hash * 31 + slug.charCodeAt(i)) >>> 0;
  return TAG_VARIANTS[hash % TAG_VARIANTS.length];
}

// Every distinct tag slug across all updates — drives the /tags/<slug>/ routes.
export async function getAllTagSlugs(): Promise<string[]> {
  const entries = await getCollection('updates');
  const set = new Set<string>();
  for (const entry of entries) {
    for (const tag of entry.data.tags) {
      const slug = tagSlug(tag.en);
      if (slug) set.add(slug);
    }
  }
  return [...set];
}

// Unique tags for the filter bar: {slug, label} in the given locale, sorted by
// label. Keyed by the en-derived slug so one concept stays one chip per locale.
export async function getAllTags(locale: Locale) {
  const entries = await getCollection('updates');
  const map = new Map<string, { slug: string; label: string }>();
  for (const entry of entries) {
    for (const tag of entry.data.tags) {
      const slug = tagSlug(tag.en);
      if (!slug || map.has(slug)) continue;
      map.set(slug, { slug, label: tag[locale] });
    }
  }
  return [...map.values()].sort((a, b) => a.label.localeCompare(b.label, locale));
}

// Newest-first updates carrying the given tag slug, for the /tags/<slug>/ pages.
export async function getUpdatesByTag(slug: string) {
  const all = await getSortedUpdates();
  return all.filter((entry) => entry.data.tags.some((tag) => tagSlug(tag.en) === slug));
}

// Page chrome for the standalone paginated routes. Page 1 carries the same
// wording in src/content-src/docs/index.mdx — keep the two in sync.
export const updatesPageStrings = {
  en: {
    title: 'Updates',
    description: 'Latest updates and announcements for Argonaut.',
    lead: 'The latest features, fixes, and announcements for Argonaut.',
  },
  fr: {
    title: 'Nouveautés',
    description: 'Dernières nouveautés et annonces pour Argonaut.',
    lead: 'Les dernières fonctionnalités, corrections et annonces pour Argonaut.',
  },
} as const;

// Page chrome for the per-tag filter routes (src/pages/tags/[tag]/ and
// src/pages/fr/tags/[tag]/). `label` is the localized tag name.
export const tagPageStrings = {
  en: {
    title: (label: string) => `Updates tagged “${label}”`,
    description: (label: string) => `Argonaut updates tagged “${label}”.`,
  },
  fr: {
    title: (label: string) => `Nouveautés étiquetées « ${label} »`,
    description: (label: string) => `Nouveautés Argonaut étiquetées « ${label} ».`,
  },
} as const;
